[package]
name = "server"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
rocket = "0.4.7"
rocket_contrib = "0.4.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
walkdir = "2"

